# Generated by Django 5.2.1 on 2025-05-31 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='email',
        ),
    ]
