# Generated by Django 5.2.1 on 2025-06-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='messeage',
            field=models.TextField(max_length=100),
        ),
    ]
